### ISSUE TITLE
Implement API auth routes 

### ISSUE THREAD

**Issue by YaraZan** [YaraZan/cloud-filer-php-vanilla#74]
- [x] `/register` route should take 4 params: name, email, password, confirm_password.
Response will be redirected to `/login` route.
- [x] `/login` route should take 2 params: email and password
Response will return jwt-token
- [ ] `/reset_password` route should take 3 arguments: old_password, new_password, confirm_password

**Comment by YaraZan** [comment]
Change `UserService` meta and impl class method `resetPassword()` to get 3 arguments: old_password, new_password, confirm_password

**Comment by YaraZan** [comment]
Change `login()` method in `UserService` impl class to actually verify user password

**Comment by YaraZan** [comment]
Add `NotAuthorizedException` class with error message "Not Authorized"

**Comment by YaraZan** [comment]
Fix middleware logic.

- Add `Route` class with path, method and controller vars.
 - Add `middleware()` method to register middleware.

**Comment by YaraZan** [comment]
Add abstract controller core class

**Comment by YaraZan** [comment]
Add `BaseException` file with `NotFoundException` class

**Comment by YaraZan** [comment]
Change property types causing error

`<br />
<b>Fatal error</b>:  Uncaught TypeError: Cannot assign string to property App\Core\Route::$controller of type App\Core\Controller in C:\xampp\htdocs\cloud-filer\src\Core\Route.php:12
Stack trace:
#0 C:\xampp\htdocs\cloud-filer\src\Core\Router.php(13): App\Core\Route-&gt;__construct('App\\Controllers...', 'register')
#1 C:\xampp\htdocs\cloud-filer\index.php(13): App\Core\Router-&gt;__construct()
#2 {main}
  thrown in <b>C:\xampp\htdocs\cloud-filer\src\Core\Route.php</b> on line <b>12</b><br />
`

**Comment by YaraZan** [comment]
Resolve JSON decode issues.

`<br />
<b>Fatal error</b>: Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, array given in
C:\xampp\htdocs\cloud-filer\src\Core\Request.php:22
Stack trace:
#0 C:\xampp\htdocs\cloud-filer\src\Core\Request.php(22): json_decode(Array)
#1 C:\xampp\htdocs\cloud-filer\src\Controllers\AuthController.php(17): App\Core\Request-&gt;getData()
#2 C:\xampp\htdocs\cloud-filer\src\Core\Route.php(25):
App\Controllers\AuthController-&gt;register(Object(App\Core\Request))
#3 C:\xampp\htdocs\cloud-filer\src\Core\Router.php(36): App\Core\Route-&gt;navigate(Object(App\Core\Request))
#4 C:\xampp\htdocs\cloud-filer\index.php(21): App\Core\Router-&gt;processRequest(Object(App\Core\Request))
#5 {main}
thrown in <b>C:\xampp\htdocs\cloud-filer\src\Core\Request.php</b> on line <b>22</b><br />`

**Comment by YaraZan** [comment]
Fixed. 

Resolve `UserService` repository issues. For this, change `DB` core class and its extended repositories by removing static logic.

**Comment by YaraZan** [comment]
Fixed.

Resolve SQL issues.

`<br />
<b>Fatal error</b>: Uncaught RuntimeException: Database query error: SQLSTATE[42000]: Syntax error or access violation:
1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the
right syntax to use near '' at line 1 in C:\xampp\htdocs\cloud-filer\src\Core\DB.php:50
Stack trace:
#0 C:\xampp\htdocs\cloud-filer\src\Core\DB.php(81): App\Core\DB-&gt;executeQuery('SELECT * FROM u...', Array, false)
#1 C:\xampp\htdocs\cloud-filer\src\Services\Impl\UserService.php(55): App\Core\DB-&gt;findOneWhere('email = ',
'yara@example.co...')
#2 C:\xampp\htdocs\cloud-filer\src\Controllers\AuthController.php(17): App\Services\Impl\UserService-&gt;register(Array)
#3 C:\xampp\htdocs\cloud-filer\src\Core\Route.php(25):
App\Controllers\AuthController-&gt;register(Object(App\Core\Request))
#4 C:\xampp\htdocs\cloud-filer\src\Core\Router.php(36): App\Core\Route-&gt;navigate(Object(App\Core\Request))
#5 C:\xampp\htdocs\cloud-filer\index.php(27): App\Core\Router-&gt;processRequest(Object(App\Core\Request))
#6 {main}
thrown in <b>C:\xampp\htdocs\cloud-filer\src\Core\DB.php</b> on line <b>50</b><br />`

**Comment by YaraZan** [comment]
Remove custom exceptions. Change logic to base `Exception class`.

**Comment by YaraZan** [comment]
Done. 

`/register` route works.

**Comment by YaraZan** [comment]
Done.

/login route works.

**Comment by YaraZan** [comment]
Create `validate` method to check request variables for specific rules and define them as required

**Comment by YaraZan** [comment]
Add `headers` property to `Request` core class. Get headers in `index.php` and add them to request class instance.

**Comment by YaraZan** [comment]
Done. 

`/resetPassword` requires different middleware logic, so it will be refactored in future issues. 

This issue now can be closed.
